### ISSUE TITLE
Release mode should compile with lto and debut stripped

### ISSUE THREAD

**Issue by mrtryhard** [mrtryhard/qt-ts-tools#19]
* If the application crashes extra symbols won't help much
* A debug build can be provided anytime

```toml
[profile.release]
lto = true
strip = true
```
